#!/usr/bin/env python

import argparse
import os
import re
import subprocess
import sys
import urllib2

# TODO: parse slides titles
# make sure mplayer is in the path


MPLAYER = 'mplayer'


def videolecture_download():
    parser = argparse.ArgumentParser(
            description='Download lectures from videolectures.net')

    parser.add_argument('url', help='http://videolectures.net/XXX/[video/NNN/]')

    parser.add_argument('-v', '--skip_video', action='store_true',
            dest='skip_video', default=False,
            help='download only slides, but no video')

    args = parser.parse_args()

    url = args.url

    html = urllib2.urlopen(url).read()

    m1 = re.search(r'clip.netConnectionUrl = "(.*?)";', html)
    m2 = re.search(r'clip.url = "(.*?)";', html)

    if m1 and m2:
        video_url = m1.group(1) + '/' + m2.group(1)
    else:
        raise Exception("Failed to find video URL")

    print 'video URL: %s' % video_url

    m = re.search(r'<meta name="title" content="(.*?)" />', html)
    title = m.group(1).rstrip()

    m = re.search(r'http://videolectures.net/([^/]*)', url)
    video_name = m.group(1)

    m = re.search(r'http://videolectures.net/(.*?)/video/(.*)', url.rstrip('/'))
    if m:
        section = m.group(2)
        video_name += '_' + section
        title += '-' + section

    #print 'Filename: %s' % video_name
    
    if not os.path.isdir(title):
        os.mkdir(title, 0755)
        print 'Lecture directory created: "%s"' % title
    else:
        print 'Lecture directory "%s" exists.' % title

    m = re.search(r'Download slides:\s*<a href="(.*?)"', html)
    slide_name = '-'
    if m:
        s_url = m.group(1)
        slide_name = s_url.split('/')[-1]
        if s_url.startswith('/'):
            s_url = 'http://videolectures.net' + s_url
        s_content = urllib2.urlopen(s_url)

        with open('%s/%s' % (title, slide_name), 'wb') as f:
            f.write(s_content.read())

    id_url = {}
    for m in re.findall(r'id: (\d+), idx: \d+, src: "(.*?)"', html):
        id_url[m[0]] = m[1]

    time_url = {}
    for m in re.findall(
            r'sync=sync.next={time: (\d+), slide: slides\[(\d+)\]', html):
        if m[1] in id_url:
            time_url[int(m[0])] = id_url[m[1]]

    with open(title + '/sync.txt', 'w') as f:
        f.write('%s\n' % video_name)

        idx = 0
        for t in sorted(time_url.keys()):
            img_url = time_url[t]
            img_ext = img_url.split('.')[-1]
            img = urllib2.urlopen(img_url)
            img_name = '%03d.%s' % (idx, img_ext)

            with open('%s/%s' % (title, img_name), 'wb') as img_file:
                img_file.write(img.read())

            f.write('%s %s\n' % (t, img_name))
            idx += 1

    with open(title + '/info.txt', 'w') as f:
        f.write('%s\n' % url)
        f.write('%s\n' % slide_name)

    if args.skip_video:
        sys.exit(0)

    video_file = '%s/%s' % (title, video_name)
    argv = [MPLAYER, '-dumpstream', video_url, '-dumpfile', video_file]
    ret = subprocess.call(argv)

    if ret == 0:
        print 'Video downloaded successfully'
    else:
        print 'Download failed. Mplayer return code: %d' % ret


if __name__ == '__main__':
    videolecture_download()
