#!/usr/bin/env python

import argparse
import re
import urllib2


def extract_video(url):

    html = urllib2.urlopen(url).read()
    m = re.search(r"'(.*?/smil.xml)'", html)
    if m:
        info_xml_url = 'http://videolectures.net' + m.group(1)
    else:
        raise Exception("Failed to find XML URL")

    info_xml = urllib2.urlopen(info_xml_url).read()
    m = re.search(r'streamer="(rtmp://.*?)" src="(.*?)"', info_xml)
    if m:
        video_url = m.group(1) + '/' + m.group(2)
    else:
        raise Exception("Failed to find video URL")

    print video_url


def main():
    parser = argparse.ArgumentParser(
            description='Download lectures from videolectures.net')

    parser.add_argument('url', help='http://videolectures.net/XXX/[video/NNN/]')

    args = parser.parse_args()
    extract_video(args.url)


if __name__ == '__main__':
    main()
